version: '3'
services:
  spark:
    #whether you want to build the docker image comment the "image" line and uncomment "build" line
    #build: docker
    image: neuw84/spark-zeppeling:latest
    ports:
     - "8080:8080"
     - "4040:4040"
    environment:
     - ZEPPELIN_JAVA_OPTS=-Dcassandra.hosts=cassandra
    volumes:
    - ./data:/usr/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook  
    links: 
    - cassandra
    depends_on: 
    - cassandra
  cassandra:
  #spotify image for faster Cassandra startup
    image: spotify/cassandra    
    ports:
    - "9042:9042"
  cassandra-web:
    image: delermando/docker-cassandra-web:v0.4.0
    environment: 
      - CASSANDRA_HOST_IP=192.168.99.100
      - CASSANDRA_PORT=9042    
    ports:
     - "3000:3000"
    links: 
    - cassandra
    depends_on: 
    - cassandra